# Generated by Django 5.2.9 on 2025-12-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВОР')),
                ('object_name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'ВОР',
                'verbose_name_plural': 'ВОР',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(help_text='Общая площадь раздела в квадратных метрах', verbose_name='Общая площадь раздела (м²)')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='estimates.estimate', verbose_name='ВОР')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_sections', to='reference.workcategory', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Раздел ВОР',
                'verbose_name_plural': 'Разделы ВОР',
                'ordering': ['estimate', 'work_category'],
                'unique_together': {('estimate', 'work_category')},
            },
        ),
        migrations.CreateModel(
            name='EstimateSectionWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Процент площади раздела, который занимает данный тип работ (сумма должна быть 100%)', verbose_name='Процент от площади раздела')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='estimates.estimatesection', verbose_name='Раздел ВОР')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_section_work_types', to='reference.worktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Тип работ в разделе',
                'verbose_name_plural': 'Типы работ в разделах',
                'ordering': ['section', '-percentage'],
                'unique_together': {('section', 'work_type')},
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(help_text='Рассчитывается автоматически на основе площади раздела, процента и объема работы на единицу типа работ', verbose_name='Объем работы')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='reference.work', verbose_name='Работа')),
                ('section_work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimatesectionworktype', verbose_name='Тип работ в разделе')),
            ],
            options={
                'verbose_name': 'Работа в ВОР',
                'verbose_name_plural': 'Работы в ВОР',
                'ordering': ['section_work_type', 'work'],
                'unique_together': {('section_work_type', 'work')},
            },
        ),
        migrations.CreateModel(
            name='EstimateItemResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Рассчитывается автоматически на основе объема работы', verbose_name='Количество ресурса')),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='estimates.estimateitem', verbose_name='Работа в ВОР')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_item_resources', to='reference.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Ресурс работы в ВОР',
                'verbose_name_plural': 'Ресурсы работ в ВОР',
                'ordering': ['estimate_item', 'resource'],
                'unique_together': {('estimate_item', 'resource')},
            },
        ),
    ]
