# Generated by Django 5.2.9 on 2025-12-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['section_work_type', 'work'], 'verbose_name': 'Работа в ВОР (из шаблона)', 'verbose_name_plural': 'Работы в ВОР (из шаблона)'},
        ),
        migrations.AlterModelOptions(
            name='estimateitemresource',
            options={'ordering': ['estimate_item', 'resource'], 'verbose_name': 'Ресурс работы в ВОР (из шаблона)', 'verbose_name_plural': 'Ресурсы работ в ВОР (из шаблона)'},
        ),
        migrations.AlterModelOptions(
            name='estimatesection',
            options={'ordering': ['estimate', 'work_category'], 'verbose_name': 'Вид работ в ВОР', 'verbose_name_plural': 'Виды работ в ВОР'},
        ),
        migrations.AlterModelOptions(
            name='estimatesectionworktype',
            options={'ordering': ['section', '-percentage'], 'verbose_name': 'Тип работ в разделе ВОР', 'verbose_name_plural': 'Типы работ в разделах ВОР'},
        ),
    ]
