# Generated by Django 5.2.9 on 2025-12-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование ресурса')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вида работ')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа работ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='reference.workcategory', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Типы работ',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.FloatField(help_text='Сколько ресурса требуется на одну единицу работы (зависит от типа работ)', verbose_name='Количество на единицу работы')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_resources', to='reference.resource', verbose_name='Ресурс')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_resources', to='reference.work', verbose_name='Работа')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_resources', to='reference.worktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Ресурс работы',
                'verbose_name_plural': 'Ресурсы работ',
                'ordering': ['work_type', 'work', 'resource'],
                'unique_together': {('work_type', 'work', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='WorkTypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок следования')),
                ('work_volume_per_unit', models.FloatField(default=1.0, help_text='Объем работы (в единицах измерения работы) на единицу типа работ. Например, м³ стяжки на 1 м² типа работ', verbose_name='Объем работы на единицу типа работ')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_works', to='reference.work', verbose_name='Работа')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_works', to='reference.worktype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Работа в типе работ',
                'verbose_name_plural': 'Работы в типах работ',
                'ordering': ['work_type', 'order_index'],
                'unique_together': {('work_type', 'work')},
            },
        ),
    ]
